app/groups/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SelectField, \
    SubmitField
from wtforms.validators import required, Length, Email, Regexp
from wtforms import ValidationError
from flask.ext.pagedown.fields import PageDownField
from wtforms.widgets import TextArea
from ..models import GroupRole, User, PostGroup, GroupMemberShip

class EditMemberShipRoleForm(Form):
    role = SelectField('Role', coerce=int)
    submit = SubmitField('Submit')
    cancel = SubmitField('Cancel')

    def __init__(self, user_id, group_id, *args, **kwargs):
        super(EditMemberShipRoleForm, self).__init__(*args, **kwargs)
        self.user = User.query.filter_by(id=user_id).first_or_404()
        self.group = PostGroup.query.filter_by(id=group_id).first_or_404()

        self.role.choices = [(role.id, role.name)
                             for role in GroupRole.query.order_by(GroupRole.name).all()]
        self.membership = GroupMemberShip.query.filter_by(member_id=user_id, group_id=group_id).first_or_404()
        self.choice_map = dict(self.role.choices)



class GroupForm(Form):
    groupname = StringField('Group Name', validators=[required(), Length(1, 64)])
    description = StringField('Description', widget=TextArea())
    submit = SubmitField('Submit')

    def validate_groupname(self, field):
        if PostGroup.exists(field.data):
            raise ValidationError("Groupname already exists. Please choose a different one.")



class AddMembersForm(Form):
    invites = StringField('Invite Members', widget=TextArea())
    submit = SubmitField('Invite')
    cancel = SubmitField('Cancel')

    def __init__(self, group_id, *args, **kwargs):
        super(AddMembersForm, self).__init__(*args, **kwargs)
        self.group = PostGroup().query.filter_by(id=group_id).first_or_404()

    def validate_invites(self, field):
        for invitee in map(lambda x: x.strip(), field.data.split(',')):

            if not '@' in invitee:
                user = User().query.filter_by(username=invitee)
                if user.count()  == 0:
                    raise ValidationError('User does not exist')
                user = user.first()
                if user in self.group.users:
                    raise ValidationError('User %s is already in the group' % (user.username,))



class ConfirmationForm(Form):
    sure = SubmitField('Yes, I am sure!')
    cancel = SubmitField('No, take me back!')

app/groups/__init__.py
from flask import Blueprint

groups = Blueprint('groups', __name__)

from . import views
from ..models import Permission


# makes the Permission class available to all templates
@groups.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/groups/views.py
from flask import render_template, redirect, url_for, abort, flash, request, \
    current_app, make_response
from flask.ext.login import login_required, current_user
from flask.ext.sqlalchemy import get_debug_queries
from . import groups
from .forms import GroupForm, EditMemberShipRoleForm, AddMembersForm, ConfirmationForm
from .. import db
from ..models import Permission, GroupRole, User, Post, Comment, PostGroup, GroupMemberShip, GroupInvite
from .errors import forbidden
from .decorators import group_permission_required
from ..email import send_email

@groups.route('/edit-membership/<int:group_id>/<int:user_id>', methods=['GET', 'POST'])
@login_required
@group_permission_required(Permission.ADMINISTER, groupvar='group_id')
def edit_membership_role(user_id, group_id):
    # invite more members only if I can administer

    ms = GroupMemberShip.query.filter_by(member_id=user_id, group_id=group_id).first_or_404()

    form = EditMemberShipRoleForm(user_id=user_id, group_id=group_id)

    if form.validate_on_submit():
        if form.cancel.data:
            return redirect(url_for('.group', id=group_id))
        elif form.submit.data:
            if ms.member_can(Permission.ADMINISTER) \
                    and GroupRole.query.filter_by(id=form.role.data).first().name != 'Owner' \
                    and form.group.count_administrators() < 2:
                flash("A group needs at least one owner.")
            else:
                ms.role = GroupRole.query.get(form.role.data)
                db.session.add(ms)
                flash("%s's role has been updated to %s" % (ms.user.username, form.choice_map[form.role.data]))
                return redirect(url_for('.group', id=group_id))
    else:
        form.role.data = ms.grouprole_id

    return render_template('edit_membership.html', form=form)

@groups.route('/delete-membership/<int:group_id>/<int:user_id>', methods=['GET', 'POST'])
@login_required
@group_permission_required(Permission.ADMINISTER, groupvar='group_id')
def delete_membership(group_id, user_id):
    group = PostGroup.query.filter_by(id=group_id).first_or_404()
    user = User.query.filter_by(id=user_id).first_or_404()
    gm =  GroupMemberShip.query.filter_by(group_id=group_id, member_id=user_id).first_or_404()

    # we don't want to delete the last administrator
    if gm.member_can(Permission.ADMINISTER) and group.count_administrators() < 2:
        flash("You don't want to delete the last administrator.")
        return redirect(url_for('.group', id=group_id))


    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.sure.data:
            gm =  GroupMemberShip.query.filter_by(group_id=group_id, member_id=user_id).first_or_404()
            db.session.delete(gm)
            flash('%s has been deleted from %s' % (gm.user.username, gm.group.groupname))
            return redirect(url_for('main.user', username=current_user.username))
        else:
            return redirect(url_for('.group', id=group_id))

    return render_template('groups/delete_membership.html', form=form)

@groups.route('/leave-group/<int:group_id>', methods=['GET', 'POST'])
@login_required
def leave_group(group_id):
    group = PostGroup.query.filter_by(id=group_id).first_or_404()

    if not current_user in group.users:
        flash("You can't leave a group you are not a member of.")
        return redirect(url_for('main.user', username=current_user.username))

    gm = group.memberships.filter_by(member_id=current_user.id).first_or_404()

    # we don't want to delete the last administrator
    if gm.member_can(Permission.ADMINISTER) and group.count_administrators() < 2:
        flash("You can't leave. You are the last administrator.")
        return redirect(url_for('.group', id=group_id))

    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.sure.data:
            db.session.delete(gm)
            flash('You have left from %s' % (gm.group.groupname, ))
            return redirect(url_for('main.user', username=current_user.username))
        else:
            return redirect(url_for('.group', id=group_id))

    return render_template('groups/leave_group.html', form=form)



@groups.route('/group/<int:id>',  methods=['GET', 'POST'])
@login_required
def group(id):
    group = PostGroup.query.filter_by(id=id).first_or_404()
    if not current_user.is_member_of(group):
        return forbidden('You do not have the rights to see this group!')

    return render_template('groups/group.html', group=group, me=current_user)


@groups.route('/edit-group/<int:group_id>', methods=['GET', 'POST'])
@login_required
@group_permission_required(Permission.ADMINISTER, groupvar='group_id')
def edit_group(group_id):
    form = GroupForm()
    pg = PostGroup.query.filter_by(id=group_id).first_or_404()
    if form.validate_on_submit():
        pg.description = form.description.data
        pg.groupname = form.groupname.data

        db.session.add(pg)
        db.session.commit()

        flash('Group %s has been updated' % (form.groupname.data,))
        return redirect(url_for('.group', id=pg.id))
    else:
        form.description.data = pg.description
        form.groupname.data = pg.groupname

    return render_template('groups/edit_group.html', form=form, title='Edit Group')

@groups.route('/create-group', methods=['GET', 'POST'])
@login_required
def create_group():
    form = GroupForm()
    if form.validate_on_submit():

        pg = PostGroup(groupname=form.groupname.data,
                       description=form.description.data)
        gm = GroupMemberShip()
        gm.group = pg
        gm.role = GroupRole.query.filter_by(name='Owner').first_or_404()
        current_user.groupmemberships.append(gm)

        db.session.add(pg)
        db.session.add(gm)
        db.session.commit()

        flash('Group %s has been created' % (form.groupname.data,))
        return redirect(url_for('.group', id=pg.id))
    return render_template('groups/edit_group.html', form=form, title='Create Group')

@groups.route('/delete-group/<int:group_id>', methods=['GET', 'POST'])
@login_required
@group_permission_required(Permission.ADMINISTER, groupvar='group_id')
def delete_group(group_id):
    group = PostGroup.query.filter_by(id=group_id).first_or_404()

    form = ConfirmationForm()
    if form.validate_on_submit():
        if form.sure.data:
            for gm in group.memberships:
                db.session.delete(gm)
            db.session.delete(group)
            flash('Group %s has been deleted' % (group.groupname, ))
            return redirect(url_for('main.user', username=current_user.username))
        else:
            return redirect(url_for('.group', id=group_id))

    return render_template('groups/delete_group.html', form=form)

@groups.route('/add-group-members/<int:group_id>', methods=['GET', 'POST'])
@login_required
@group_permission_required(Permission.ADMINISTER, groupvar='group_id')
def add_group_members(group_id):

    form = AddMembersForm(group_id)
    if form.validate_on_submit():
        for invitee in map(lambda x: x.strip(), form.invites.data.split(',')):
            with db.session.no_autoflush:
                kwargs = {'group_id':group_id}
                user_exists = False
                if '@' in invitee:
                    kwargs['email'] = invitee
                else:
                    user = User.query.filter_by(username=invitee)
                    user = user.first_or_404()
                    kwargs['email'] = user.email
                    kwargs['user_id'] = user.id
                    user_exists = True

                gi = GroupInvite(**kwargs)
                if user_exists:
                    send_email(user.email, 'You have been invited to join %s at Labloid' % (form.group.groupname, ),
                               'groups/email/confirm', user=user, other=current_user, group=gi.group)
                else:
                    send_email(kwargs['email'], 'You have been invited to join Labloid',
                               'auth/email/invitation', user=current_user, token=gi.generate_confirmation_token())

                flash('A invitation to join %s has been sent out.' % (form.group.groupname, ))
                db.session.add(gi)

            db.session.commit()

        return redirect(url_for('.group', id=form.group.id))
    return render_template('groups/add_members.html', form=form)



@groups.route('/confirm-group/<token>')
def confirm_group(token):
    if GroupInvite.confirm(token, current_user):
        flash('Groupmembership confirmed!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('main.user', username=current_user.username))

@groups.route('/decline-invite/<token>')
def decline_invite(token):
    if GroupInvite.decline(token):
        flash('Invite declined!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('main.user', username=current_user.username))

app/templates/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('.user', username=comment.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author"><a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
            <div class="comment-body">
                {% if comment.disabled %}
                <p></p><i>This comment has been disabled by a moderator.</i></p>
                {% endif %}
                {% if moderate or not comment.disabled %}
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                {% endif %}
            </div>
            {% if moderate %}
                <br>
                {% if comment.disabled %}
                <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable', id=comment.id, page=page) }}">Enable</a>
                {% else %}
                <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">Disable</a>
                {% endif %}
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('.edit', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}
                <a href="{{ url_for('.post', id=post.id) }}">
                    <span class="label label-default">Permalink</span>
                </a>
                <a href="{{ url_for('.post', id=post.id) }}#comments">
                    <span class="label label-primary">{{ post.comments.count() }} Comments</span>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Labloid{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Labloid</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/edit_membership.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Labloid - Edit Membership{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Membership of {{ form.user.username }} in {{ form.group.groupname }}</h1>
</div>

<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/group.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Labloid - {{ group.groupname }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="profile-header">
        <h1>Group {{ group.groupname }}</h1>

        <p>Founded {{ moment(group.timestamp).format('L') }}. </p>

        <p>{{ group.description }}</p>
    </div>

</div>
<div  class="page-content">
    <h2>Members</h2>
        <table class="table table-hover followers">
        <thead>
        <tr>
            <th>User</th>
            <th>Joined</th>
            <th>Role</th>
            <th>Edit</th>
        </tr>
        </thead>
        {% for membership in group.memberships %}
        <tr>
            <td>
                <a href="{{ url_for('.user', username = membership.user.username) }}">
                    <img class="img-rounded" src="{{ membership.user.gravatar(size=32) }}">
                    {{ membership.user.username }}
                </a>
            </td>
            <td>{{ moment(membership.timestamp).format('L') }}</td>
            <td>{{ membership.role.name }}</td>
            <td>
                {% if group.is_administrator(me) %}
                <a href="{{ url_for('.edit_membership', user_id=membership.user.id, group_id=group.id) }}">
                    <button type="button" class="btn btn-default ">Edit Membership</button>
                </a>
                {% else %}
                <button type="button" class="btn btn-default disabled">Edit Membership</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if group.is_administrator(me) %}
    <h2>Invite More Members</h2>
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    {% endif %}

</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Labloid{% endblock %}

{% block page_content %}
<div class="page-header">
    {% if current_user.is_authenticated() %}
    <h1>Hello {{ current_user.username }}</h1>
    {% else %}
    <h1>Labloid</h1>
    <h4>a shared lab journal using IPython notebooks and git</h4>
    {% endif %}
</div>


<div class="post-tabs">

    {% if not current_user.is_authenticated() %}

    <p>
        Please <a href="{{ url_for('auth.login') }}">login</a> if you want to see your current posts or <a
            href="{{ url_for('auth.register') }}">register</a> as a new user.
    </p>


    {% endif %}
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Labloid - {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">
    <div class="profile-header">
        <h1>{{ user.username }}
            <small>
                {% if user.name %}{{ user.name }}{% endif %}
                {% if user == current_user %}
                    <a class="btn btn-primary pull-right" href="{{ url_for('.edit_profile') }}">Edit Profile</a>
                {% elif current_user.is_administrator() %}
                    <a class="btn btn-danger pull-right" href="{{ url_for('.edit_profile_admin', id=user.id) }}">Edit Profile [Admin]</a>
                {% endif %}
            </small>

        </h1>
        <p>
            {% if user.location %}
                From <a href="http://maps.google.com/?q={{ user.location }}">{{ user.location }}</a><br>
            {% endif %}

        </p>

        {% if current_user.is_administrator() %}
        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        <p>Member since {{ moment(user.member_since).format('L') }}. Last seen {{ moment(user.last_seen).fromNow() }}.</p>
        <p>
        </p>
    </div>

    {% if user == current_user and user.invites.count() > 0 %}
        <h3>Pending Group Invites</h3>
    <p>
    <table class="table table-striped followers">
        <thead>
        <tr>
            <th>Group</th>
            <th>Actions</th>
        </tr>
        </thead>
            {% for gi in user.invites %}
                <tr>
                    <td>
                        {{ gi.group.groupname }}
                    </td>
                    <td>
                         <a href="{{ url_for('groups.confirm_group', token=gi.generate_confirmation_token()) }}">
                            <button type="button" class="btn btn-default ">Confirm</button>
                        </a>
                         <a href="{{ url_for('groups.decline_invite', token=gi.generate_confirmation_token()) }}">
                            <button type="button" class="btn btn-default ">Decline</button>
                        </a>
                    </td>
                </tr>
        {% endfor %}
    </table>
    </p>

    {% endif %}

    {% if user == current_user %}
    <h3>Your Groups
        <small>
            <a class="btn btn-primary pull-right" href="{{ url_for('groups.create_group') }}">Create New Group</a>
        </small>
    </h3>
    <p>
        {% for gm in user.groupmemberships %}
            <a class="btn btn-info" href="{{ url_for('groups.group', id=gm.group_id) }}">{{ gm.group.groupname }} </a>
        {% endfor %}
    </p>
    {% endif %}


</div>

{% endblock %}